# Generated by Django 6.0.1 on 2026-03-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
