# Generated by Django 5.2.8 on 2025-12-23 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanreport',
            name='scan_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
