# Generated by Django 5.2.8 on 2025-12-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_alter_scanreport_scan_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanreport',
            options={'ordering': ['-scan_date']},
        ),
        migrations.AlterField(
            model_name='scanreport',
            name='result_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='scanreport',
            name='scan_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scanreport',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scanreport',
            name='target_url',
            field=models.CharField(max_length=255),
        ),
    ]
