# Generated by Django 6.0.1 on 2026-03-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_userprofile_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='webhook_threshold',
            field=models.CharField(choices=[('all', 'All Vulnerabilities'), ('medium', 'Medium and Above'), ('high', 'High and Critical Only')], default='all', max_length=10),
        ),
    ]
