# Generated by Django 6.0.3 on 2026-03-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_userprofile_webhook_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanreport',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
