# Generated by Django 6.0.3 on 2026-03-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_scanreport_is_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanreport',
            name='schedule_interval',
            field=models.IntegerField(default=0),
        ),
    ]
