# Generated by Django 6.0.3 on 2026-04-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_scanreport_schedule_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanreport',
            name='schedule_interval',
        ),
        migrations.AddField(
            model_name='scanreport',
            name='cron_expression',
            field=models.CharField(default='', max_length=100),
        ),
    ]
