# Generated by Django 6.0.3 on 2026-04-30 05:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_remove_scanreport_schedule_interval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OASTEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('headers', models.TextField(blank=True, null=True)),
                ('payload', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
